baseURL = "https://soraya97.github.io/VeilleTechno/"
languageCode = "en-us"
title = "Veille UX Design"
theme = "harbor2" 
[taxonomies]
  category = "categories"
  tag = "tags"

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 3

[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "tags"
  weight = 3

[[params.nav]]
  identifier = "categories"
  name = "Category"
  icon = "fas fa-folder-open fa-lg"
  url = "categories"
  weight = 3

[params.logo]
  url = "logo_v2_250.png"
  width = 50
  height = 50
  alt = "Logo"